apiVersion: v1
kind: Pod
metadata:
  annotations:
    workflows.argoproj.io/node-name: text-analysisvr7dl.extract-data(0)
    workflows.argoproj.io/template: '{"name":"extract-data-template","arguments":{},"inputs":{},"outputs":{"artifacts":[{"name":"meta","path":"/usr/src/app/meta.json","ipfs":{"hash":"","storageEndpoint":"http://ipfs-cluster:9094/add"}},{"name":"content","path":"/usr/src/app/text.txt","ipfs":{"hash":"","storageEndpoint":"http://ipfs-cluster:9094/add"}}]},"nodeSelector":{"kubernetes.io/arch":"arm"},"metadata":{},"container":{"name":"","image":"ipfs-companion:5000/ciqojt27jw6fuaaxrckof2z5z23nryjj2r5movbsc6nyvy5gm2tnlsq","command":["sh","-c"],"args":["npm
      start /worker_data/draft-ali-pce-remote-initiated-gmpls-lsp-00.pdf"],"resources":{"requests":{"cpu":"2"}},"volumeMounts":[{"name":"datavol","mountPath":"/worker_data"}]},"volumes":[{"name":"datavol","hostPath":{"path":"/home/pi/sample","type":"Directory"}}],"retryStrategy":{}}'
  creationTimestamp: "2019-12-30T14:22:28Z"
  deletionGracePeriodSeconds: 30
  deletionTimestamp: "2019-12-30T14:29:05Z"
  labels:
    workflows.argoproj.io/completed: "false"
    workflows.argoproj.io/workflow: text-analysisvr7dl
  name: text-analysisvr7dl-555070617
  namespace: default
  ownerReferences:
  - apiVersion: argoproj.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Workflow
    name: text-analysisvr7dl
    uid: 08b1acc5-48af-4de4-a824-9d954c70496a
  resourceVersion: "542975"
  selfLink: /api/v1/namespaces/default/pods/text-analysisvr7dl-555070617
  uid: 3261d00c-ff0c-4fd7-a853-ecbeb2618992
spec:
  containers:
  - command:
    - argoexec
    - wait
    env:
    - name: ARGO_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: ARGO_CONTAINER_RUNTIME_EXECUTOR
      value: pns
    - name: ARGO_KUBELET_HOST
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
    image: theduske/argoexec:multi
    imagePullPolicy: IfNotPresent
    name: wait
    resources: {}
    securityContext:
      capabilities:
        add:
        - SYS_PTRACE
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /argo/podmetadata
      name: podmetadata
    - mountPath: /mainctrfs/worker_data
      name: datavol
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-cpl5l
      readOnly: true
  - args:
    - npm start /worker_data/draft-ali-pce-remote-initiated-gmpls-lsp-00.pdf
    command:
    - sh
    - -c
    image: ipfs-companion:5000/ciqojt27jw6fuaaxrckof2z5z23nryjj2r5movbsc6nyvy5gm2tnlsq
    imagePullPolicy: Always
    name: main
    resources:
      requests:
        cpu: "2"
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /worker_data
      name: datavol
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-cpl5l
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: raspberrypi
  nodeSelector:
    kubernetes.io/arch: arm
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  shareProcessNamespace: true
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - downwardAPI:
      defaultMode: 420
      items:
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.annotations
        path: annotations
    name: podmetadata
  - hostPath:
      path: /home/pi/sample
      type: Directory
    name: datavol
  - name: default-token-cpl5l
    secret:
      defaultMode: 420
      secretName: default-token-cpl5l
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2019-12-30T14:22:28Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2019-12-30T14:23:30Z"
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2019-12-30T14:22:35Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2019-12-30T14:22:28Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://a015e40c0d80c5c90783064dd06f5e90e9efcadf322284b695e5f933695d24bb
    image: ipfs-companion:5000/ciqojt27jw6fuaaxrckof2z5z23nryjj2r5movbsc6nyvy5gm2tnlsq:latest
    imageID: ipfs-companion:5000/ciqojt27jw6fuaaxrckof2z5z23nryjj2r5movbsc6nyvy5gm2tnlsq@sha256:fe4e7a5ba2060a0bfee4d4c6ccf42fbdfc8182a46a32d655b3f67d1b6fe71359
    lastState: {}
    name: main
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2019-12-30T14:22:34Z"
  - containerID: containerd://d566413b62b14b2c498d95ff140bf9f54b9c21d53241d8e35f1a5c39f9e86f5a
    image: docker.io/theduske/argoexec:multi
    imageID: docker.io/theduske/argoexec@sha256:32704514b9094a8373d78b9b9914cb5fcc3ac5f5fb34584e39abd24ed384064d
    lastState: {}
    name: wait
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2019-12-30T14:22:31Z"
  hostIP: 192.168.2.27
  phase: Running
  podIP: 10.42.4.60
  podIPs:
  - ip: 10.42.4.60
  qosClass: Burstable
  startTime: "2019-12-30T14:22:28Z"
