version: '3.5'
services:
  server:
    image: k3s-ipfs:4.0-4.2
    build:
      # Path to the Docker file
      context: ./image
    command: "server --disable-agent --no-deploy traefik"
    privileged: true
    environment:
      - K3S_CLUSTER_SECRET=test
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
    volumes:
      - k3s-server:/var/lib/rancher/k3s
      - .:/output
      - ./ipfsconfig/swarm.key:/root/.ipfs/swarm.key
    ports:
      - 6443:6443
    networks: 
      - cluster

  node:
    image: k3s-ipfs:4.0-4.2
    build:
      # Path to the Docker file
      context: ./image
    tmpfs:
      - /run
      - /var/run
    privileged: true
    command: "agent"
    depends_on:
      - server
    volumes:
      - ./ipfsconfig/swarm.key:/root/.ipfs/swarm.key
    environment:
      - K3S_URL=https://server:6443
      - K3S_CLUSTER_SECRET=test
    networks: 
      - cluster

  ipfsnode:
    image: ipfs/go-ipfs:v0.4.20
    environment:
      - IPFS_PROFILE=local-discovery
    volumes:
      - ./ipfsconfig/swarm.key:/data/ipfs/swarm.key
      - ./ipfsdata:/import
    networks:
      - cluster

volumes:
  k3s-server: {}

networks:
  cluster: