version: '3.5'
services:
  server:
    image: k3s-0.7.0
    build:
      # Path to the Docker file
      context: ./image
    command: "server --kubelet-arg='address=0.0.0.0' --no-deploy traefik" #--disable-agent
    privileged: true
    environment:
      - K3S_CLUSTER_SECRET=test
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
      #- IPFS_BOOTSTRAP=/ip4/192.168.65.2/tcp/4001/ipfs/QmTEahS782n8YWvcXvKQGyPqrHJ6WT2AENTwe1ooybRBZi
    volumes:
      - k3s-server:/var/lib/rancher/k3s
      - .:/output
      - ./ipfsconfig/swarm.key:/root/.ipfs/swarm.key
    ports:
      - 6443:6443
    networks: 
      - cluster

  node:
    image: k3s-0.7.0
    build:
      # Path to the Docker file
      context: ./image
    tmpfs:
      - /run
      - /var/run
    privileged: true
    command: "agent --kubelet-arg='eviction-hard=imagefs.available<5%,nodefs.available<5%,memory.available<6000Mi'"
    depends_on:
      - server
    volumes:
      - ./ipfsconfig/swarm.key:/root/.ipfs/swarm.key
    environment:
      - K3S_URL=https://server:6443
      - K3S_CLUSTER_SECRET=test
      #- IPFS_BOOTSTRAP=/ip4/192.168.65.2/tcp/4001/ipfs/QmTEahS782n8YWvcXvKQGyPqrHJ6WT2AENTwe1ooybRBZi
    networks: 
      - cluster
volumes:
  k3s-server: {}

networks:
  cluster: