version: '3.5'
services:
  server:
    image: rancher/k3s:v0.8.0
    command: "server --kubelet-arg='address=0.0.0.0' --no-deploy traefik" #--disable-agent
    privileged: true
    environment:
      - K3S_CLUSTER_SECRET=test
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
      - CONTAINERD_LOG_LEVEL=debug
    volumes:
      - k3s-server:/var/lib/rancher/k3s
      - ./image/config.toml.tmpl:/var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl
      - .:/output
    ports:
      - 6443:6443
      - 5001:5001 # IPDR PORT for pushing images
    networks: 
      - cluster

  node:
    image: rancher/k3s:v0.8.0
    tmpfs:
      - /run
      - /var/run
    privileged: true
    command: "agent --kubelet-arg='eviction-hard=imagefs.available<5%,nodefs.available<5%,memory.available<6000Mi'"
    depends_on:
      - server
    volumes:
      - ./ipfsconfig/swarm.key:/root/.ipfs/swarm.key
      - ./image/config.toml.tmpl:/var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl
    environment:
      - K3S_URL=https://server:6443
      - K3S_CLUSTER_SECRET=test
      - CONTAINERD_LOG_LEVEL=debug
    networks: 
      - cluster
volumes:
  k3s-server: {}

networks:
  cluster: