version: '3.5'
services:
  server:
    image: k3s-ipfs:4.0
    command: "server --disable-agent --no-deploy traefik"
    privileged: true
    environment:
      - K3S_CLUSTER_SECRET=test
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
    volumes:
      - k3s-server:/var/lib/rancher/k3s
      - .:/output
      - ./ipfsconfig/swarm.key:/root/.ipfs/swarm.key
    ports:
      - 6443:6443
    networks: 
      - cluster

  node:
    image: k3s-ipfs:4.0
    tmpfs:
      - /run
      - /var/run
    privileged: true
    command: "agent"
    depends_on:
      - server
    volumes:
      - ./ipfsconfig/swarm.key:/root/.ipfs/swarm.key
    environment:
      - K3S_URL=https://server:6443
      - K3S_CLUSTER_SECRET=test
    networks: 
      - cluster

volumes:
  k3s-server: {}

networks:
  cluster: