apiVersion: apps/v1
kind: Deployment
metadata:
  name: memtest-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: memtest
  template:
    metadata:
      labels:
        app: memtest
    spec:
      containers:
      - name: memtest-container
        image: polinux/stress
        command: ["stress"]
        args: ["--vm", "1", "--vm-bytes", "500M", "--vm-hang", "1"]