apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ipfs-companion
  namespace: default
spec:
  selector:
    matchLabels:
      name: ipfs-companion
  template:
    metadata:
      labels:
        name: ipfs-companion
    spec:
      volumes:
        - name: ipfs-storage
          hostPath:
            path: /data
        - name: secrets
          secret:
            secretName: secret-config
      containers:
        - name: ipdr
          image: theduske/ipdr:oci
          imagePullPolicy: Always
          command:
            - /bin/sh
            - -c
            - |
              /app/ipdr server --ipfs-gateway https://127.0.0.1:8080
          ports:
            - name: reg
              protocol: TCP
              containerPort: 5000
              hostPort: 5000
        - name: goipfs
          image: theduske/ipfs-multiarch:v0.4.22
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              ipfs init
              ipfs config Addresses.API /ip4/0.0.0.0/tcp/5001
              ipfs config Addresses.Gateway /ip4/0.0.0.0/tcp/8080
              cp /secrets/swarm.key /data/ipfs/swarm.key
              ipfs bootstrap rm --all
              ipfs  bootstrap add /dns4/${SVC_NAME}-0.${SVC_NAME}/tcp/4001/ipfs/${IPFS_PEER_ID} 
              ipfs daemon --migrate=true
          env:
            - name: SVC_NAME
              value: "ipfs-cluster"
            - name: IPFS_FD_MAX
              value: "4096"
            - name: IPFS_PEER_ID
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: ipfs-bootstrap-peer-id
            - name: IPFS_SWARM_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-config
                  key: swarm.key
          volumeMounts:
            - name: ipfs-storage
              mountPath: /data/ipfs
            - name: secrets
              mountPath: /secrets
              readOnly: true  
          ports:
            - name: swarm
              protocol: TCP
              containerPort: 4001
            - name: swarm-udp
              protocol: UDP
              containerPort: 4002
            - name: api
              protocol: TCP
              containerPort: 5001
              hostPort: 5001
            - name: ws
              protocol: TCP
              containerPort: 8081
            - name: http
              protocol: TCP
              containerPort: 8080
              hostPort: 8555
          readinessProbe:
            httpGet:
              path: /api/v0/id
              port: api
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
