apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: text-analysis
spec:
  entrypoint: extract-data
  templates:
  - name: extract-data
    dag:
      tasks:
      - name: extract-data
        template: extract-data-template
      
      - name: guess-language
        dependencies: [extract-data]
        template: guess-language
        arguments:
          artifacts:
          - name: text
            from: "{{tasks.extract-data.outputs.artifacts.content}}" 
      
      - name: core-phrases
        dependencies: [extract-data]
        template: core-phrases
        arguments:
          artifacts:
          - name: text
            from: "{{tasks.extract-data.outputs.artifacts.content}}" 

      - name: stats
        dependencies: [extract-data]
        template: stats
        arguments:
          artifacts:
          - name: text
            from: "{{tasks.extract-data.outputs.artifacts.content}}" 
      
      - name: keywords
        dependencies: [extract-data]
        template: keywords
        arguments:
          artifacts:
          - name: text
            from: "{{tasks.extract-data.outputs.artifacts.content}}" 

      - name: merger
        dependencies: [guess-language, stats, keywords, core-phrases]
        template: merger
        arguments:
          artifacts:
          - name: meta
            from: "{{tasks.extract-data.outputs.artifacts.meta}}"  
          - name: language
            from: "{{tasks.guess-language.outputs.artifacts.language}}"
          - name: stats
            from: "{{tasks.stats.outputs.artifacts.stats}}"   
          - name: keywords
            from: "{{tasks.keywords.outputs.artifacts.keywords}}"   
          - name: core-phrases
            from: "{{tasks.core-phrases.outputs.artifacts.core-phrases}}"       

  - name: extract-data-template
    nodeSelector:
      node-role.kubernetes.io/worker: true
    container:
      # registry.gitlab.cc-asp.fraunhofer.de:4567/dchabrowski/distributed-analysis-network/text-metadata-extractor:latest
      image: ipfs-companion:5000/ciqmjrloulgan5nvknwkekuukcck2cp2tab5x2uvjhj3f325t3genxa
      command: [sh, -c]
      args: ["npm start /worker_data/simplex.pdf"]
      volumeMounts:
        - mountPath: /worker_data
          name: datavol
    volumes:
    - name: datavol
      hostPath:
        path: /worker_data
        type: Directory
    outputs:
      artifacts:
      - name: meta
        path: /usr/src/app/meta.json
        ipfs:
          storageEndpoint: "http://ipfs-cluster:9094/add"
      - name: content
        path: /usr/src/app/text.txt
        ipfs:
          storageEndpoint: "http://ipfs-cluster:9094/add"

  - name: guess-language
    container:
      # registry.gitlab.cc-asp.fraunhofer.de:4567/dchabrowski/distributed-analysis-network/text-language-guesser
      image: ipfs-companion:5000/ciqfhhzayced47yof4k2cp5apxdvtqg5jihq6qampdijdfy7zrcahfq
      command: [sh, -c]
      args: ["npm start /tmp/text"]
    inputs:
      artifacts:
      - name: text
        path: /tmp/text
    outputs:
      artifacts:
      - name: language
        path: /usr/src/app/language.json
        ipfs:
          storageEndpoint: "http://ipfs-cluster:9094/add"

  - name: core-phrases
    container:
      # registry.gitlab.cc-asp.fraunhofer.de:4567/dchabrowski/distributed-analysis-network/text-language-guesser
      image: ipfs-companion:5000/ciqk6evg3tunp6tsv6xparhx544gjnoaitlsqt66ughybwwzmivboci
      command: [sh, -c]
      args: ["npm start /tmp/text"]
    inputs:
      artifacts:
      - name: text
        path: /tmp/text
    outputs:
      artifacts:
      - name: core-phrases
        path: /usr/src/app/corePhrases.json
        ipfs:
          storageEndpoint: "http://ipfs-cluster:9094/add"

  - name: stats
    container:
      # registry.gitlab.cc-asp.fraunhofer.de:4567/dchabrowski/distributed-analysis-network/text-statistican
      image: ipfs-companion:5000/ciqkmfhfgokdvvbpqbaiskatcemtyq3qcwirgnvkj5g2oawmmuc5vbq
      command: [sh, -c]
      args: ["npm start /tmp/text"]
    inputs:
      artifacts:
      - name: text
        path: /tmp/text
    outputs:
      artifacts:
      - name: stats
        path: /usr/src/app/stats.json
        ipfs:
          storageEndpoint: "http://ipfs-cluster:9094/add"

  - name: keywords
    container:
      # registry.gitlab.cc-asp.fraunhofer.de:4567/dchabrowski/distributed-analysis-network/text-keyword-extractor
      image: ipfs-companion:5000/ciqolgnteqxgsfzsq6ix3dsjoc7gldypfljbutedf273uaq4ntdbtri
      command: [sh, -c]
      args: ["npm start /tmp/text"]
    inputs:
      artifacts:
      - name: text
        path: /tmp/text
    outputs:
      artifacts:
      - name: keywords
        path: /usr/src/app/keywords.json
        ipfs:
          storageEndpoint: "http://ipfs-cluster:9094/add"

  - name: merger
    container:
      # registry.gitlab.cc-asp.fraunhofer.de:4567/dchabrowski/distributed-analysis-network/json-merger
      image: ipfs-companion:5000/ciqkfhqo7lychgh3olbky2wd7ocz3nttotjeql4qma5ot2jdbpgx7iq
      command: [sh, -c]
      args: ["npm start /tmp/jsons"]
    inputs:
      artifacts:
      - name: meta
        path: /tmp/jsons/meta.json
      - name: core-phrases
        path: /tmp/jsons/core-phrases.json
      - name: stats
        path: /tmp/jsons/stats.json
      - name: keywords
        path: /tmp/jsons/keywords.json
      - name: language
        path: /tmp/jsons/language.json
    outputs:
      artifacts:
      - name: keywords
        path: /usr/src/app/result.json
        ipfs:
          storageEndpoint: "http://ipfs-cluster:9094/add"