apiVersion: v1
kind: Pod
metadata:
  name: memory-test
spec:
  containers:
  - name: memory-test-ctr
    image: polinux/stress
    # resources:
    #   limits:
    #     memory: "4000Mi"
    #   requests:
    #     memory: "3000Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "4000M", "--vm-hang", "1"]
  nodeSelector:
    worker: limited