apiVersion: v1
kind: Pod
metadata:
  name: nginx-pd
spec:
  containers:
  - image: nginx:latest
    name: nginx-container
    volumeMounts:
    - mountPath: /data
      name: ipfs-volume
  volumes:
  - name: ipfs-volume
    hostPath:
      # directory location on host
      path: /ipfs
      # this field is optional
      type: Directory